### ISSUE TITLE
Ability to view board at the end of the game

### ISSUE THREAD

**Issue by tzyganu** [joffrey-bion/seven-wonders#117]
As a user, I would like to see my board and the other players board (wonder, cards, coins, ...) at the end of the game so I can see who played what and blame my loss on something other than my lack of skills :smile: 

Acceptance criteria:
 - A button exists anywhere on the score popup at the end of the game. 
 - Clicking that button will hide the score and show the regular playing table and an additional button that, when clicked,it shows the score again scores again.

**Comment by joffrey-bion** [comment]
Yep, this is definitely a must, I'm already tracking that one here:
https://github.com/joffrey-bion/seven-wonders/issues/59

I'll close this one as duplicate if you don't mind 😉

**Comment by tzyganu** [comment]
ah..I missed that. I won't mind.
