### ISSUE TITLE
Wonder side select should show active button of the group

### ISSUE THREAD

**Issue by ArchangelX360** [joffrey-bion/seven-wonders#120]
![image](https://user-images.githubusercontent.com/4418480/107706459-a30d2380-6cc0-11eb-8799-f1c1b9f2a619.png)

**Comment by joffrey-bion** [comment]
I have contemplated this idea before, but labeled it as "not worth the effort".

These buttons really have an instant (push) effect, there is no real persistent "state".
The only state is that of the wonders themselves, and we can't infer the buttons' state from it (a random roll could yield all As or all Bs).

To show a consistent button state for all players, it means we would need to artificially keep track of an additional independent state on the server specifically for this. I don't really like this for multiple reasons:

* 1 state tracked in 2 different places/ways allows for discrepancies
* UI-specific state on the server feels wrong
* the server's customization feature is in fact very general and allows any combination of wonders and sides to be specified by the owner of the game. I just implemented simple buttons for now, but technically *anything* could be done here, such as selecting each wonder and side individually for each player. If this is implemented, how would the button state make sense?

**Comment by ArchangelX360** [comment]
I totally agree with the point made, while trying to implement it I actually realised the issues you are listing here.

I think, as we discussed privately, probably splitting the buttons a bit, instead of making them part of what looks like a button group would be best to convey the "instant push" instead of a state to enforce.

I will close that for now.
