### ISSUE TITLE
Lighthouse card not counted

### ISSUE THREAD

**Issue by stevasale** [joffrey-bion/seven-wonders#121]
The card "Lighthouse" is currently giving no points. It should give points equivalent to the number of yellow cards present at the end of the game

**Comment by joffrey-bion** [comment]
Thanks for the report! I will check this ASAP

**Comment by joffrey-bion** [comment]
It was due to a misconfiguration. The bonus was awarded for grey cards instead of yellow.
It should be fixed by the next deploy in a couple minutes
