### ISSUE TITLE
West trading post does not give you coupon for forum

### ISSUE THREAD

**Issue by bgstack15** [joffrey-bion/seven-wonders#163]
The east trading post does, but not the west trading post.

**Comment by joffrey-bion** [comment]
Thanks for the report, I will take a look

**Comment by joffrey-bion** [comment]
I haven't reproduced yet, but this would be quite surprising given that both cards have the same "children" configuration:

https://github.com/joffrey-bion/seven-wonders/blob/main/sw-engine/src/main/resources/org/luxons/sevenwonders/engine/data/cards.json#L332
https://github.com/joffrey-bion/seven-wonders/blob/main/sw-engine/src/main/resources/org/luxons/sevenwonders/engine/data/cards.json#L269

**Comment by joffrey-bion** [comment]
Ah I think I found it. It's because the `Forum` has only a single `chainParent` set to the `East Trading Post`:
https://github.com/joffrey-bion/seven-wonders/blob/main/sw-engine/src/main/resources/org/luxons/sevenwonders/engine/data/cards.json#L741
