### ISSUE TITLE
Olympia B wonder points miscalculation

### ISSUE THREAD

**Issue by bgstack15** [joffrey-bion/seven-wonders#170]
I played with Olympia B and completed phase 3 of the wonder, which lets me duplicate a single purple card of my choice from one of my neighbors. I chose Builder's Guild which earned me 9 points based on my neighbor's and my completed wonder phases. This 9 points was counted **twice** in my total score according to the scoresheet: once in the wonder category and once in the purple category.
![2023-08-18-202319_1915x960_scrot](https://github.com/joffrey-bion/seven-wonders/assets/19957575/48995efa-976e-4b50-bbf9-2dd509e48c80)
![2023-08-18-202339_931x603_scrot](https://github.com/joffrey-bion/seven-wonders/assets/19957575/6e3d91ba-7c5d-40b6-98f5-e15ec8a351b0)
These 9 points should only be counted once in this arrangement, and I recommend only in the purple category.

**Comment by joffrey-bion** [comment]
Oh my, thanks for the report. I think I had overcorrected when fixing the opposite issue:
https://github.com/joffrey-bion/seven-wonders/issues/126

**Comment by joffrey-bion** [comment]
Regarding counting it as wonder or purple, I would say I'm now leaning towards counting it as wonder points. After all, you didn't play a purple card to get these points, these are points that were granted by your winder.

There is an [interesting thread](https://boardgamegeek.com/thread/642884/article/6652480#6652480) about counting this copied guild as an actual purple card, and after much debate, it is settled by a clarification from the Leaders extension, saying that Hiram doesn't grant points for the copied guild, meaning it's not a guild card.
