### ISSUE TITLE
Font Issue in firefox

### ISSUE THREAD

**Issue by stevasale** [joffrey-bion/seven-wonders#34]
The fantasy font in Firefox 70.0 on Fedora is not displayed. Manually changing to e.g. arial helps... but I think it is some addon causing this, as others on firefox do not have this issue

**Comment by joffrey-bion** [comment]
Hi, thanks for reporting this. I should probably embed (or link to) a specific font to ensure consistency across browsers.

**Comment by joffrey-bion** [comment]
The issue should be fixed now when the CI/CD pipeline is done redeploying. Please don't hesitate to reopen if you still have problems with the font.
Also, please don't hesitate to open other issues if you see something wrong.
