### ISSUE TITLE
Feature request: Dont mix A and B sides

### ISSUE THREAD

**Issue by stevasale** [joffrey-bion/seven-wonders#35]
The option to either play
1) Only A
2) Only B
3) Allow the player to choose which side to play
4) Random, as it is right now
would be nice.
The default random choice could potentially lead to unbalanced games.
Thanks in advance

**Comment by joffrey-bion** [comment]
Thanks for your input!

This is a fair point. It was initially planned and then I postponed it for higher priority features.

This is actually almost already supported. I just need to add the UI for it, but the server supports it.
