### ISSUE TITLE
Too many points for war

### ISSUE THREAD

**Issue by stevasale** [joffrey-bion/seven-wonders#41]
Some players get 28 points for war even though only 18 are possible

**Comment by joffrey-bion** [comment]
Thanks for reporting this. I will take a look ASAP

**Comment by joffrey-bion** [comment]
It looks like this happens when one of the players has the "copy guild" special move at the end of the game.
This move most likely triggers the end of 3rd age a second time, giving a second time the points for military victories of the 3rd age.
I will fix this.
