### ISSUE TITLE
Cant open new game

### ISSUE THREAD

**Issue by stevasale** [joffrey-bion/seven-wonders#48]
It is impossible to start a new game. Neither hitting enter nor clicking the "plus"  button work (tested on FF on Linux, Chromium on Linux, FF on Mac, Safari)

**Comment by joffrey-bion** [comment]
Thanks for opening this issue. I didn't realize some recent updates had been published.
Will fix ASAP.

**Comment by joffrey-bion** [comment]
Looks like it was due to some broken existing game.
After restart everything looks fine
