### ISSUE TITLE
'Ready' button not indicating click action

### ISSUE THREAD

**Issue by stevasale** [joffrey-bion/seven-wonders#56]
The 'ready' button does not change colour/indicate you clicked it nor does the counter show how many people have clicked 'ready'.
This is cosmetic only. The game is still playable. 

While on the subject: is it really necessary to click 'ready' after every playing action?

**Comment by joffrey-bion** [comment]
Thanks for reporting this. I tend to test a lot with bots that play really fast, so I must have missed this.
This is definitely a bug, and could confirm it right now.

The reason for the "ready" button is to give the time for each player to check the moves of other players after a turn, and ensure everyone gets their hand at the same time.
It doesn't matter much at the moment, but it will become critical once I implement the timer feature (https://github.com/joffrey-bion/seven-wonders/issues/3).
It does feel annoying at times, though. Maybe I should make it an optional feature in the settings, but that would complicate things to an extent.

**Comment by joffrey-bion** [comment]
@stevasale the removal of "ready" button is tracked in https://github.com/joffrey-bion/seven-wonders/issues/63
