### ISSUE TITLE
Allow to browse the boards at end of game

### ISSUE THREAD

**Issue by joffrey-bion** [joffrey-bion/seven-wonders#59]
Currently the scoreboard is modal and doesn't allow to check out the other boards for a "debriefing".
This is usually a nice moment at the end of the game, we want to allow this!

**Comment by bgstack15** [comment]
Yes, would you please add this feature! I don't know Kotlin, but I would hope it's easy to move this entire summary window into a dialog you can minimize/show, and the "leave" button could be on the main page. My friends and I would like to review how the scores came to be and this feature would be very helpful on our game nights.

**Comment by joffrey-bion** [comment]
I kinda let that one slip my mind, but if you're interested I'll certainly look into it!

**Comment by bgstack15** [comment]
If you use developer tools in the browser to delete node
```
<div class="bp3-overlay bp3-overlay-open">
```
underneath object `<div class="bp3-portal">` then you can view the board and everything like normal, but now the "Leave" button is gone.
Perhaps if you could please make this summary a little button visible on the main view, beside the "leave" button. Then a person could flip between the summary, and the board, and then also press leave from the main view when done.
