### ISSUE TITLE
Persist redux state across refresh

### ISSUE THREAD

**Issue by joffrey-bion** [joffrey-bion/seven-wonders#9]
Following [this stackoverflow thread](http://stackoverflow.com/questions/37195590/how-can-i-keep-redux-state-tree-on-refresh), we should probably use one of [redux-persist](https://www.npmjs.com/package/redux-persist) or [redux-storage](https://www.npmjs.com/package/redux-storage).

**Comment by joffrey-bion** [comment]
This is somehow linked to https://github.com/luxons/seven-wonders/issues/10

**Comment by victorchabbert** [comment]
This should be done after we are done with the definition of the state tree.
Persisting a changing tree will just burden us while we develop.

**Comment by joffrey-bion** [comment]
Refreshing actually closes the websocket connection with the server.
What we need is proper support for reconnection rather than client-side state storage.
Closing in favor of https://github.com/joffrey-bion/seven-wonders/issues/10
