### ISSUE TITLE
Generate random usernames on landing page

### ISSUE THREAD

**Issue by viAtom** [joffrey-bion/seven-wonders#95]
The username input is blank by default with a placeholder, it could be nice and useful to put a button next to the input that could fill the input with a random 'cool' username (like Yafnag or others)

as a reference : https://dicelog.com/yafnagfr

**Comment by joffrey-bion** [comment]
Any suggestion for a random name generator API?

I've found this: https://www.fantasynamegenerators.com, it's very rich and very cool, but not really computer friendly.
Everything is generated in JS... 😞 

This one has an easy API and looks OK: https://donjon.bin.sh/fantasy/name/

**Comment by viAtom** [comment]
I just looked a bit further into generators and maybe a greek name generators would be more immersive ? This one looked cool : https://mex1co.github.io/agnames/

The code of this one is native js https://codepen.io/MeX1Co/pen/ZwNvva, we could take only the first name generation part, names are dope

ex: 'Aclepides', 'Alkikles'

**Comment by joffrey-bion** [comment]
> maybe a greek name generators would be more immersive ?

Good point, let's do this.

> I think adapting code from JS is better than calling an API when we want a name

100% agreed. Given the simplicity I'm ok with that.

I'm just not too fond of putting tons of data in the frontend code itself (that's more stuff to download for a feature that maybe no-one needs 😄), but it looks quite small actually.

**Comment by viAtom** [comment]
> I'm just not too fond of putting tons of data in the frontend code itself (that's more stuff to download for a feature that maybe no-one needs 😄), but it looks quite small actually.

We can still adapt the code in kotlin and serve multiple names on demand with a basic route for the front to call
